---
id: sinatrasapporo-20141220
base_name: 2013-14-season
tags:
- rabbit
- sinatrasapporo
presentation_date: 2014/12/20
version: 2014.12.20.0
licenses:
  - CC BY-NC-ND 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
